# Generated by Django 4.2.3 on 2023-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('ids', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='书籍编码')),
                ('isbn', models.CharField(max_length=30, unique=True, verbose_name='ISBN编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='书名')),
                ('press', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='出版社')),
                ('type', models.CharField(default='', max_length=50, verbose_name='分类')),
                ('price', models.FloatField(blank=True, default='0.0', null=True, verbose_name='定价')),
                ('count', models.IntegerField(default='0', verbose_name='数量')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
            },
        ),
    ]
